datagrid:
    issues-grid:
        extended_entity_name: '%oroacademic_issue.entity.class%'
        acl_resource: oroacademic_issue_view
        source:
            type: orm
            query:
                select:
                    - issue.id
                    - issue.summary
                    - issue.code
                    - issue.type
                    - ip.name as priority
                    - ip.label as priorityLabel
                    - workflowStep.label as workflowStepLabel
                    - ir.name as resolution
                    - ir.label as resolutionLabel
                    - CONCAT(rpt.firstName, CONCAT(' ', rpt.lastName)) as reporterName
                    - rpt.id as reporter
                    - CONCAT(asg.firstName, CONCAT(' ', asg.lastName)) as assigneeName
                    - asg.id as assignee
                    - GROUP_CONCAT(collaborators.id) as collaborator
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: '%oroacademic_issue.entity.class%', alias: issue }
                join:
                    left:
                        - { join: issue.priority, alias: ip }
                        - { join: issue.resolution, alias: ir }
                        - { join: issue.reporter, alias: rpt }
                        - { join: issue.assignee, alias: asg }
                        - { join: issue.workflowStep, alias: workflowStep }
                        - { join: issue.collaborators, alias: collaborators }
                groupBy: issue.code
        inline_editing:
            enable: true
        columns:
            code:
                label:         oroacademic.issue.code.label
            summary:
                label:         oroacademic.issue.summary.label
            type:
                label:         oroacademic.issue.type.label
            priority:
                label:         oroacademic.issue.priority.label
                frontend_type: select
            workflowStepLabel:
                label:         oroacademic.issue.workflow_step.label
            resolution:
                label:         oroacademic.issue.resolution.label
                frontend_type: select
            reporterName:
                label:         oroacademic.issue.reporter.label
            assigneeName:
                label:         oroacademic.issue.assignee.label
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                code:
                    data_name: issue.code
                type:
                    data_name: issue.type
                workflowStepLabel:
                    data_name: workflowStep.stepOrder
                priority:
                    data_name: ip.order
                reporterName:
                    data_name: reporterName
                assigneeName:
                    data_name: assigneeName
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type:      string
                    data_name: issue.code
                summary:
                    type:      string
                    data_name: issue.summary
                type:
                    label: oroacademic.issue.type.label
                    type: choice
                    data_name: issue.type
                    options:
                        field_options:
                              multiple: true
                              choices: '%oroacademic_issue.types%'
                priority:
                    label: oroacademic.issue.priority.label
                    type: entity
                    data_name: ip.label
                    options:
                        field_options:
                              class: OroAcademicIssueBundle:IssuePriority
                              multiple: true
                              property: label
                              translatable_options: false
                workflowStepLabel:
                    type:      entity
                    data_name: issue.workflowStep
                    options:
                        field_type: oro_workflow_step_select
                        field_options:
                            multiple: true
                            workflow_entity_class: '%oroacademic_issue.entity.class%'
                resolution:
                    label: oroacademic.issue.resolution.label
                    type:      entity
                    data_name: ir.label
                    options:
                        field_options:
                              class: OroAcademicIssueBundle:IssueResolution
                              multiple: true
                              property: label
                              translatable_options: false
                reporter:
                    type: choice-tree
                    label: oroacademic.issue.reporter.label
                    data_name: issue.reporter
                    options:
                        lazy: '@oro_user.provider.filter.user_choice_tree->shouldBeLazy'
                        data: '@?oro_user.provider.filter.user_choice_tree->getList'
                assegnee:
                    type: choice-tree
                    label: oroacademic.issue.assignee.label
                    data_name: issue.assignee
                    options:
                        lazy: '@oro_user.provider.filter.user_choice_tree->shouldBeLazy'
                        data: '@?oro_user.provider.filter.user_choice_tree->getList'
                collaborators:
                    label:     Collaborators
                    type:      choice-tree
                    data_name: collaborators.id
                    options:
                        lazy: '@oro_user.provider.filter.user_choice_tree->shouldBeLazy'
                        data: '@?oro_user.provider.filter.user_choice_tree->getList'
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      oroacademic_issue_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oroacademic_issue_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oroacademic_api_delete_issue
                params:     [ id ]
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                acl_resource:  oroacademic_issue_view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                label:         oro.grid.action.update
                acl_resource:  oroacademic_issue_update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                label:         oro.grid.action.delete
                acl_resource:  oroacademic_issue_delete
                icon:          trash
                link:          delete_link
        options:
            entity_pagination: true
    sub-issues-grid:
            extends: issues-grid
            source:
                query:
                    where:
                        and:
                            - issue.parent = :parent_id
                bind_parameters:
                    - parent_id
            filters: ~
            options:
                toolbarOptions:
                    hide: true
    rel-issues-grid:
                extends: issues-grid
                source:
                    query:
                        where:
                            and:
                                - issue.id IN (:ids)
                    bind_parameters:
                        - ids
                filters: ~
                options:
                    toolbarOptions:
                        hide: true
    collaborators-grid:
                extends: users-grid
                source:
                    query:
                        where:
                            and:
                                - u.id IN (:ids)
                    bind_parameters:
                        - ids
                filters: ~
                options:
                    toolbarOptions:
                        hide: true
    user-issues-grid:
                extends: issues-grid
                source:
                    query:
                        where:
                            and:
                                - issue.assignee = :userId or issue.reporter = :userId
                    bind_parameters:
                        - userId
                filters: ~
                options:
                    toolbarOptions:
                        hide: true
    widget-issues-grid:
                extends: issues-grid
                source:
                    query:
                        where:
                            and:
                                - collaborators.id = :userId
                                - workflowStep.name NOT IN ('closed')
                    bind_parameters:
                        - userId
                filters: ~
                options:
                    toolbarOptions:
                        hide: true
                        pageSize:
                            items: [10]
                            default_per_page: 10