parameters:
    oroacademic_issue.form.type.issue.class:              OroAcademic\Bundle\IssueBundle\Form\Type\IssueType
    oroacademic_issue.form.handler.task.class:            OroAcademic\Bundle\IssueBundle\Form\Handler\IssueHandler

services:
    oroacademic_issue.form.type.issue:
        class: %oroacademic_issue.form.type.issue.class%
        arguments: [%oroacademic_issue.types%]
        tags:
            - { name: form.type, alias: oroacademic_issue }

    oroacademic_issue.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'oroacademic_issue'
            - 'oroacademic_issue'

    oroacademic_issue.form.handler.issue:
        class: %oroacademic_issue.form.handler.task.class%
        scope: request
        arguments:
            - @oroacademic_issue.form
            - @request
            - @doctrine.orm.entity_manager
            - @oro_activity.manager
            - @oro_entity.routing_helper
