parameters:
    oroacademic_issue.form.type.issue.class:              OroAcademic\Bundle\IssueBundle\Form\Type\IssueType
    oroacademic_issue.form.type.issue_api.class:          OroAcademic\Bundle\IssueBundle\Form\Type\IssueApiType
    oroacademic_issue.form.handler.issue.class:           OroAcademic\Bundle\IssueBundle\Form\Handler\IssueHandler
    oroacademic_issue.form.handler.issue_api.class:       OroAcademic\Bundle\IssueBundle\Form\Handler\IssueApiHandler
    oroacademic_issue.manager.api.class:                  Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    oroacademic_issue.form.type.issue:
        class: '%oroacademic_issue.form.type.issue.class%'
        arguments: ['%oroacademic_issue.types%']
        tags:
            - { name: form.type, alias: oroacademic_issue }

    oroacademic_issue.form.type.issue_api:
            class: '%oroacademic_issue.form.type.issue_api.class%'
            arguments: ['%oroacademic_issue.types%']
            tags:
                - { name: form.type, alias: oroacademic_issue_api }

    oroacademic_issue.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', 'createNamed']
        arguments:
            - oroacademic_issue
            - oroacademic_issue

    oroacademic_issue.form.api:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', 'createNamed']
        arguments:
            - oroacademic_issue_api
            - oroacademic_issue_api

    oroacademic_issue.form.handler.issue:
        class: '%oroacademic_issue.form.handler.issue.class%'
        scope: request
        arguments:
            - '@oroacademic_issue.form'
            - '@request'
            - '@doctrine.orm.entity_manager'

    oroacademic_issue.form.handler.issue_api:
                class: '%oroacademic_issue.form.handler.issue_api.class%'
                scope: request
                arguments:
                    - '@oroacademic_issue.form.api'
                    - '@request'
                    - '@doctrine.orm.entity_manager'
                    - '@oro_security.security_facade'

    oroacademic_issue.manager.api:
            class: '%oroacademic_issue.manager.api.class%'
            parent: oro_soap.manager.entity_manager.abstract
            arguments:
                - '%oroacademic_issue.entity.class%'
                - '@doctrine.orm.entity_manager'