parameters:
    issue.importexport.class: OroAcademic\Bundle\IssueBundle\ImportExport\TemplateFixture\IssueFixture

services:
    orocacademic.importexport.template_fixture.issue:
        class: '%issue.importexport.class%'
        tags:
            - { name: oro_importexport.template_fixture }

    orocacademic.importexport.template_fixture.data_converter.issue:
        parent: oro_importexport.data_converter.template_fixture.configurable

    orocacademic.importexport.data_converter.issue:
        parent: oro_importexport.data_converter.configurable

    orocacademic.importexport.processor.export_template.issue:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@orocacademic.importexport.template_fixture.data_converter.issue']]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: '%oroacademic_issue.entity.class%', alias: oroacademic_issue_template }

    orocacademic.importexport.processor.export.issue:
        parent: oro_importexport.processor.export_abstract
        calls:
             - [setDataConverter, ['@orocacademic.importexport.data_converter.issue']]
        tags:
            - { name: oro_importexport.processor, type: export, entity: '%oroacademic_issue.entity.class%', alias: oroacademic_issue_export }

    orocacademic.importexport.strategy.issue.add_or_replace:
        parent: oro_importexport.strategy.configurable_add_or_replace

    orocacademic.importexport.processor.import.issue:
        parent: oro_importexport.processor.import_abstract
        calls:
          - [setDataConverter, ['@orocacademic.importexport.data_converter.issue']]
          - [setStrategy, ['@orocacademic.importexport.strategy.issue.add_or_replace']]
        tags:
          - { name: oro_importexport.processor, type: import, entity: '%oroacademic_issue.entity.class%', alias: oroacademic_issue_import }
          - { name: oro_importexport.processor, type: import_validation, entity: '%oroacademic_issue.entity.class%', alias: oroacademic_issue_import }