placeholders:
    view_content_data_additional_information:
        items:
            oroacademic_user_issues: ~
    view_navButtons_before:
        items:
            oroacademic_user_issues_create_btn: ~

items:
    oroacademic_user_issues:
        template: OroAcademicIssueBundle:Issue:userIssues.html.twig
        applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)'
        acl: oroacademic_issue_view
    oroacademic_user_issues_create_btn:
        template: OroAcademicIssueBundle:Issue:userButton.html.twig
        applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)'
        acl: oroacademic_issue_create
