parameters:
    oroacademic_issue.entity.class:                       OroAcademic\Bundle\IssueBundle\Entity\Issue
    oroacademic_issue.note.listener.class:                OroAcademic\Bundle\IssueBundle\EventListener\NoteListener
    oroacademic_issue.entity.listener.class:              OroAcademic\Bundle\IssueBundle\EventListener\IssueEntityListener
    oroacademic_issue.grid.listener.class:              OroAcademic\Bundle\IssueBundle\EventListener\GridListener
    oroacademic_issue.types.provider.class:               OroAcademic\Bundle\IssueBundle\Provider\IssueTypesProvider

    oroacademic_issue.types:
        - { name: Bug, type: main }
        - { name: Task, type: main }
        - { name: Subtask, type: sub }
        - { name: Story, type: main }

services:
    oroacademic_issue.types.provider:
        class: '%oroacademic_issue.types.provider.class%'
        arguments:
            - '%oroacademic_issue.types%'

    oroacademic_issue.note.listener:
        class: '%oroacademic_issue.note.listener.class%'
        tags:
          - { name: doctrine.event_listener, event: prePersist, method: prePersist }

    oroacademic_issue.entity.listener:
        class: '%oroacademic_issue.entity.listener.class%'
        arguments:
            - '@oro_navigation.content.topic_sender'
        tags:
            - { name: doctrine.orm.entity_listener }

    oroacademic_issue.grid.listener:
            class: '%oroacademic_issue.grid.listener.class%'
            tags:
                - { name: kernel.event_listener, event: kernel.view, method: onKernelView }